// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPTB41-xCPuhS-wu7A1ARzDDWv4cN1SYs',
    appId: '1:985173915718:web:3af3592b8d58414eab3247',
    messagingSenderId: '985173915718',
    projectId: 'pomodoroapps-raion',
    authDomain: 'pomodoroapps-raion.firebaseapp.com',
    storageBucket: 'pomodoroapps-raion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuM5OaqgDNJbgT9SCV_rwSsuL8N2lmRps',
    appId: '1:985173915718:android:1379b7a36fdaa90bab3247',
    messagingSenderId: '985173915718',
    projectId: 'pomodoroapps-raion',
    storageBucket: 'pomodoroapps-raion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCYqSnKXIZ3hBA4v9ydjtCbKqM-DARhk',
    appId: '1:985173915718:ios:701e5e8af2584720ab3247',
    messagingSenderId: '985173915718',
    projectId: 'pomodoroapps-raion',
    storageBucket: 'pomodoroapps-raion.appspot.com',
    iosBundleId: 'com.example.pomodoroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCYqSnKXIZ3hBA4v9ydjtCbKqM-DARhk',
    appId: '1:985173915718:ios:701e5e8af2584720ab3247',
    messagingSenderId: '985173915718',
    projectId: 'pomodoroapps-raion',
    storageBucket: 'pomodoroapps-raion.appspot.com',
    iosBundleId: 'com.example.pomodoroApp',
  );
}
